[package]
name = "mqtt_broker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.5.0"
pretty_env_logger = "0.4.0"
rumqttd = "0.11.0"
